# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def shared_pods
	use_frameworks!
	pod 'Cider', '~> 0.10'
	pod 'Hue'
	pod 'SwiftLint'
end

# Pods for Kasha
target 'Kasha' do
	shared_pods
end
