# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def shared_pods
	use_frameworks!
	pod 'Hue'
	pod 'MarqueeLabel/Swift'
	pod 'SwiftIcons', '~> 2.0.1'
	pod 'SwiftLint'
end

# Pods for Kasha
target 'Kasha' do
	shared_pods
	pod 'AppCenter'
	pod 'BDKCollectionIndexView'
    pod 'DeckTransition', '~> 2.0'
	pod 'ViewAnimator'
end
