# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def shared_pods
	use_frameworks!
	pod 'Hue'
	pod 'SwiftLint'
	pod 'Texture'
end

# Pods for Kasha
target 'Kasha' do
	shared_pods
end
